name: notes_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  provider: ^6.1.4
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - .env


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center