name: notes_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.8.1
  http: ^1.3.0
  injectable: ^2.5.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.5.0
  provider: ^6.1.4
  retrofit: ^4.4.2
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1
  very_good_analysis: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/splash.png
    - .env


flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center